version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:16.0
      - image: redis
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Checkout submodule
          command: |
            git submodule update --init
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Test
          command: |
            ./gradlew check jacocoTestReport
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: Build
          command: |
            ./gradlew clean :app:bootJar
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Deployment
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ./.circleci/setup-heroku.sh
              ./.circleci/setup-retry.sh
              retry -- heroku plugins:install java
              retry -- heroku deploy:jar \
                --jar app/build/libs/app.jar \
                --jdk 16 \
                --app $HEROKU_APP
            fi
